---
# Homebrew Configuration
homebrew_taps:
  - 0xmachos/mosl
  - 1password/tap
  - apple/apple
  - buo/cask-upgrade
  - cjbassi/gotop
  - felixkratz/formulae
  - jamf/tap
  - jayadamsmorgan/yatoro
  - jeffreywildman/virt-manager
  - jlhonora/lsusb
  - jzaleski/jzaleski
  - kismetwireless/kismet
  - krtirtho/apps
  - mas-cli/tap
  - minacle/chntpw
  - nikitabobko/tap
  - pakerwreah/calendr
  - rcmdnk/file
  - real-aazam/aazam
  - sidneys/homebrew
  - yulrizka/tap

homebrew_installed_packages:
  - aircrack-ng
  - ansible
  - ansiweather
  - aria2
  - arp-scan
  - autoconf-archive
  - automake
  - awk
  - bash
  - bash-completion
  - bash-snippets
  - bat
  - bettercap
  - binwalk
  - bluetoothconnector
  - blueutil
  - boost-python3
  - btop
  - cabextract
  - calc
  - cask
  - ccache
  - cdrtools
  - chezmoi
  - cmake
  - cmatrix
  - cmus
  - composer
  - czkawka
  - entr
  - fastfetch
  - fdupes
  - findutils
  - fortune
  - fping
  - freerdp
  - gedit
  - gemini-cli
  - genact
  - git
  - glances
  - gnu-indent
  - gnu-tar
  - gnu-which
  - gnupg
  - go
  - google-authenticator-libpam
  - graphviz
  - gtk+
  - handbrake
  - highlight
  - hstr
  - htop
  - httpie
  - hub
  - ifstat
  - imagemagick
  - iperf
  - kubernetes-cli
  - libnotify
  - libtermkey
  - libvterm
  - llvm@20
  - luarocks
  - m-cli
  - mackup
  - macosvpn
  - macvim
  - mas
  - masscan
  - mdk
  - midnight-commander
  - minicom
  - mist-cli
  - mkvtoolnix
  - mosh
  - mpv
  - msgpack
  - mtr
  - musikcube
  - mycli
  - mysql-client
  - nasm
  - ncdu
  - neofetch
  - neovim
  - netdata
  - ninja
  - nmap
  - nnn
  - nowplaying-cli
  - ntopng
  - openconnect
  - openvpn
  - parallel
  - passwdqc
  - pipx
  - powershell
  - protobuf-c
  - putty
  - pv
  - python@3.10
  - python@3.11
  - python@3.9
  - qemu
  - qpdf
  - qt
  - ranger
  - rbenv
  - rcm
  - recon-ng
  - redis
  - rename
  - rsync
  - rust
  - sevenzip
  - shpotify
  - sleepwatcher
  - snort
  - speedtest-cli
  - switchaudio-osx
  - tcl-tk
  - telnet
  - terminal-notifier
  - terraform
  - the_silver_searcher
  - thefuck
  - tiger-vnc
  - tldr
  - tmux
  - topgrade
  - transmission-cli
  - trash
  - virt-manager
  - w3m
  - watch
  - wget
  - wifi-password
  - wimlib
  - ykman
  - zsh
  - zsh-completions

homebrew_cask_apps:
  - 1password
  - 1password-cli
  - aerial
  - aerospace
  - antigravity
  - appcleaner
  - applite
  - autopkgr
  - beeper
  - blockblock
  - brooklyn
  - caffeine
  - calibre
  - chrome-remote-desktop-host
  - crescendo
  - cryptomator
  - dhs
  - discord
  - docker
  - docker-desktop
  - fing
  - font-3270-nerd-font
  - font-agave-nerd-font
  - font-anonymice-nerd-font
  - font-arimo-nerd-font
  - font-aurulent-sans-mono-nerd-font
  - font-bigblue-terminal-nerd-font
  - font-bitstream-vera-sans-mono-nerd-font
  - font-blex-mono-nerd-font
  - font-caskaydia-cove-nerd-font
  - font-code-new-roman-nerd-font
  - font-cousine-nerd-font
  - font-daddy-time-mono-nerd-font
  - font-dejavu-sans-mono-nerd-font
  - font-droid-sans-mono-nerd-font
  - font-fantasque-sans-mono-nerd-font
  - font-fira-code-nerd-font
  - font-fira-mono-nerd-font
  - font-go-mono-nerd-font
  - font-gohufont-nerd-font
  - font-hack-nerd-font
  - font-hasklug-nerd-font
  - font-heavy-data-nerd-font
  - font-hurmit-nerd-font
  - font-im-writing-nerd-font
  - font-inconsolata-go-nerd-font
  - font-inconsolata-lgc-nerd-font
  - font-inconsolata-nerd-font
  - font-iosevka-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-lekton-nerd-font
  - font-liberation-nerd-font
  - font-m+-nerd-font
  - font-meslo-lg-nerd-font
  - font-monaspace-nerd-font
  - font-monaspice-nerd-font
  - font-monofur-nerd-font
  - font-monoid-nerd-font
  - font-mononoki-nerd-font
  - font-noto-nerd-font
  - font-open-dyslexic-nerd-font
  - font-opendyslexic-nerd-font
  - font-overpass-nerd-font
  - font-profont-nerd-font
  - font-proggy-clean-tt-nerd-font
  - font-roboto-mono-nerd-font
  - font-sauce-code-pro-nerd-font
  - font-shure-tech-mono-nerd-font
  - font-space-mono-nerd-font
  - font-terminess-ttf-nerd-font
  - font-tinos-nerd-font
  - font-ubuntu-mono-nerd-font
  - font-ubuntu-nerd-font
  - font-victor-mono-nerd-font
  - gas-mask
  - google-chrome@beta
  - handbrake
  - handbrake-app
  - iina
  - iterm2
  - jdownloader
  - keka
  - kid3
  - knockknock
  - logi-options+
  - losslessswitcher
  - lulu
  - maccy
  - makemkv
  - microsoft-auto-update
  - microsoft-excel
  - microsoft-onenote
  - microsoft-outlook
  - microsoft-powerpoint
  - microsoft-teams
  - microsoft-word
  - mist
  - netiquette
  - network-radar
  - nordvpn
  - obs
  - openemu
  - oversight
  - packages
  - platypus
  - plex
  - powershell@preview
  - pppc-utility
  - profilecreator
  - proxyman
  - qbittorrent
  - qflipper
  - qmk-toolbox
  - quakenotch
  - raspberry-pi-imager
  - remoteviewer
  - sf-symbols
  - shuttle
  - sloth
  - sonos
  - soundsource
  - spotube
  - steam
  - stremio
  - suspicious-package
  - taskexplorer
  - tempbox
  - thaw@beta
  - transmission
  - tunnelblick
  - utm
  - virtualbuddy
  - visual-studio-code
  - vlc
  - vnc-viewer
  - whatsyoursign
  - windows-app
  - wireshark
  - wireshark-app
  - xcodes
  - xcodes-app
  - xld
  - zed
  - zen
  - zenmap

# Mac App Store Apps (id: can be found with `mas search <app_name>`)
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 441258766, name: "Magnet" }

# macOS System Defaults
macos_defaults:
  - { domain: 'com.apple.finder', key: 'AppleShowAllFiles', type: 'bool', value: 'true' }
  - { domain: 'com.apple.finder', key: 'ShowPathbar', type: 'bool', value: 'true' }
  - { domain: 'com.apple.dock', key: 'autohide', type: 'bool', value: 'true' }
  - { domain: 'NSGlobalDomain', key: 'KeyRepeat', type: 'int', value: '2' }
  - { domain: 'NSGlobalDomain', key: 'InitialKeyRepeat', type: 'int', value: '15' }
