---
- name: Install Rustup
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: ~/.cargo/bin/rustc

- name: Install Cargo packages
  ansible.builtin.shell: ~/.cargo/bin/cargo install {{ item }}
  loop: "{{ cargo_packages }}"
  changed_when: false
