---
- hosts: local
  connection: local
  gather_facts: true
  
  vars_files:
    - group_vars/all.yml
    - group_vars/apps_extra.yml

  pre_tasks:
    - name: Ensure Homebrew is in PATH (Apple Silicon)
      ansible.builtin.lineinfile:
        path: ~/.zprofile
        line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
        create: true
      when: ansible_architecture == "arm64"

    - name: Ensure Homebrew is in PATH (Intel)
      ansible.builtin.lineinfile:
        path: ~/.zprofile
        line: 'eval "$(/usr/local/bin/brew shellenv)"'
        create: true
      when: ansible_architecture == "x86_64"
      
  roles:
    - homebrew
    - mas
    - macos
    - dotfiles
    - rcm
    - vscode
    - rust
    - python
    - node
    - php
    - powershell
    - tldr
